# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [28]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [29]:
cars1 = pd.read_csv('C:cars1.csv', sep = ',' )
cars2 = pd.read_csv('C:cars2.csv', sep = ',' )

### Step 4. Ops it seems our first dataset has some unnamed blank columns, fix cars1

In [30]:
cars1 = cars1.dropna(axis='columns',how='all')
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199,97,2774,15.5,70,1,amc hornet
17,21.0,6,200,85,2587,16.0,70,1,ford maverick
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104,95,2375,17.5,70,2,saab 99e
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360,215,4615,14.0,70,1,ford f250
26,10.0,8,307,200,4376,15.0,70,1,chevy c20
27,11.0,8,318,210,4382,13.5,70,1,dodge d200
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
168,23.0,4,140,83,2639,17.0,75,1,ford pinto
169,20.0,6,232,100,2914,16.0,75,1,amc gremlin
170,23.0,4,140,78,2592,18.5,75,1,pontiac astro
171,24.0,4,134,96,2702,13.5,75,3,toyota corona
172,25.0,4,90,71,2223,16.5,75,2,volkswagen dasher
173,24.0,4,119,97,2545,17.0,75,3,datsun 710
174,18.0,6,171,97,2984,14.5,75,1,ford pinto
175,29.0,4,90,70,1937,14.0,75,2,volkswagen rabbit
176,19.0,6,232,90,3211,17.0,75,1,amc pacer
177,23.0,4,115,95,2694,15.0,75,2,audi 100ls
178,23.0,4,120,88,2957,17.0,75,2,peugeot 504
179,22.0,4,121,98,2945,14.5,75,2,volvo 244dl
180,25.0,4,121,115,2671,13.5,75,2,saab 99le
181,33.0,4,91,53,1795,17.5,75,3,honda civic cvcc
182,28.0,4,107,86,2464,15.5,76,2,fiat 131
183,25.0,4,116,81,2220,16.9,76,2,opel 1900
184,25.0,4,140,92,2572,14.9,76,1,capri ii
185,26.0,4,98,79,2255,17.7,76,1,dodge colt
186,27.0,4,101,83,2202,15.3,76,2,renault 12tl
187,17.5,8,305,140,4215,13.0,76,1,chevrolet chevelle malibu classic
188,16.0,8,318,150,4190,13.0,76,1,dodge coronet brougham
189,15.5,8,304,120,3962,13.9,76,1,amc matador
190,14.5,8,351,152,4215,12.8,76,1,ford gran torino
191,22.0,6,225,100,3233,15.4,76,1,plymouth valiant
192,22.0,6,250,105,3353,14.5,76,1,chevrolet nova
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [31]:
print('nbr de colonnes de cars1:',len(cars1.columns),'. Nbr de ligne:',len(cars1.index),'.')
print('nbr de colonnes de cars2:',len(cars2.columns),'. Nbr de ligne:',len(cars2.index),'.')

nbr de colonnes de cars1: 9 . Nbr de ligne: 198 .
nbr de colonnes de cars2: 9 . Nbr de ligne: 200 .

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [33]:
cars = pd.concat([cars1,cars2],axis = 0)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199,97,2774,15.5,70,1,amc hornet
17,21.0,6,200,85,2587,16.0,70,1,ford maverick
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104,95,2375,17.5,70,2,saab 99e
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360,215,4615,14.0,70,1,ford f250
26,10.0,8,307,200,4376,15.0,70,1,chevy c20
27,11.0,8,318,210,4382,13.5,70,1,dodge d200
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe
183,36.0,4,107,75,2205,14.5,82,3,honda accord
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla
185,38.0,4,91,67,1965,15.0,82,3,honda civic
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto)
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx
188,25.0,6,181,110,2945,16.4,82,1,buick century limited
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion
191,22.0,6,232,112,2835,14.7,82,1,ford granada l
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Ops there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [48]:
owners = np.random.randint(15000,high = 73000,size = 398)
owners
owners.tolist()

[45646,
 64000,
 66292,
 55892,
 31814,
 69756,
 65421,
 24549,
 46498,
 44386,
 48612,
 57496,
 59844,
 47480,
 31760,
 35005,
 55466,
 69229,
 30859,
 23769,
 71531,
 27883,
 46731,
 65441,
 36028,
 68594,
 72928,
 66696,
 22224,
 70591,
 45077,
 47840,
 67928,
 38089,
 44469,
 40460,
 48204,
 36098,
 67580,
 56897,
 16013,
 69147,
 54416,
 57727,
 26636,
 64750,
 52011,
 27108,
 35140,
 15542,
 59140,
 19551,
 58488,
 48336,
 22279,
 24654,
 23799,
 72969,
 58976,
 48845,
 48224,
 25819,
 54607,
 64838,
 47132,
 49558,
 50732,
 42114,
 38453,
 65141,
 21044,
 27675,
 47388,
 61565,
 22775,
 18280,
 61303,
 72872,
 32407,
 58324,
 26722,
 65384,
 41850,
 29818,
 46121,
 49908,
 51375,
 23219,
 48186,
 47505,
 29674,
 52420,
 43747,
 51963,
 71383,
 15625,
 24052,
 22887,
 48672,
 44442,
 25739,
 52870,
 19108,
 53120,
 48852,
 45925,
 33852,
 51792,
 20586,
 44168,
 31621,
 44653,
 50699,
 51934,
 25260,
 42720,
 16173,
 28388,
 38176,
 70218,
 47476,
 64297,
 57839,
 69418,
 21639,
 67928,
 21078,
 27777,
 16452,
 46814,
 66176,
 32056,
 63116,
 37881,
 17887,
 47064,
 51202,
 23227,
 41775,
 24522,
 47214,
 39765,
 45552,
 37324,
 16537,
 34550,
 45984,
 30276,
 27773,
 46434,
 56087,
 66238,
 54812,
 65882,
 28010,
 28477,
 71984,
 42284,
 55835,
 61051,
 34918,
 49472,
 51513,
 28558,
 17959,
 48587,
 22366,
 35712,
 70736,
 18679,
 47693,
 19291,
 41498,
 29135,
 53621,
 20919,
 52979,
 36685,
 35080,
 28914,
 17882,
 67724,
 17602,
 19842,
 52622,
 64764,
 17216,
 15209,
 17196,
 48713,
 33533,
 40815,
 53644,
 26856,
 42003,
 31864,
 67662,
 42507,
 52591,
 19495,
 43654,
 65836,
 69694,
 53524,
 43438,
 16293,
 68702,
 64066,
 33107,
 39227,
 27603,
 60500,
 18306,
 51070,
 51913,
 32377,
 34042,
 16162,
 56639,
 62040,
 41461,
 53336,
 33624,
 44637,
 44773,
 63883,
 40040,
 66989,
 42343,
 40861,
 46349,
 38195,
 40299,
 15405,
 43795,
 68279,
 44618,
 19457,
 59032,
 41630,
 57150,
 70881,
 71702,
 16480,
 50468,
 16374,
 71465,
 46112,
 34821,
 31461,
 33564,
 26318,
 15382,
 53928,
 61833,
 64800,
 63157,
 56745,
 66995,
 39140,
 34806,
 37345,
 38416,
 36468,
 44610,
 55372,
 37374,
 51397,
 63078,
 61783,
 40209,
 22405,
 72565,
 67301,
 65265,
 69931,
 28305,
 46493,
 26407,
 46553,
 57210,
 63340,
 44451,
 25948,
 57262,
 37818,
 38363,
 47893,
 29303,
 40015,
 20458,
 27282,
 68609,
 36900,
 47178,
 24336,
 71053,
 19940,
 29856,
 64371,
 33929,
 44475,
 28572,
 25825,
 32936,
 47554,
 59508,
 37337,
 35105,
 61092,
 39506,
 16631,
 24394,
 64196,
 28591,
 59330,
 34812,
 67223,
 45901,
 18394,
 70767,
 31054,
 42908,
 69268,
 46021,
 16691,
 43595,
 20591,
 71890,
 59192,
 32818,
 47596,
 44860,
 52372,
 62030,
 52907,
 65536,
 49325,
 37491,
 70278,
 66434,
 32331,
 57370,
 17565,
 41747,
 53568,
 53113,
 43196,
 71435,
 71704,
 68394,
 36697,
 26994,
 67166,
 16003,
 42774,
 72944,
 71109,
 38721,
 57059,
 39480,
 70561,
 35807,
 43292,
 57507,
 45099,
 63544,
 35290,
 55068,
 63958,
 62762,
 21623,
 24012,
 46084,
 59952,
 40286,
 60592,
 22044,
 26175,
 50845,
 18624,
 17878,
 46149,
 38344,
 25642,
 34942,
 70299,
 44030,
 44030,
 26962,
 59198,
 62642,
 22850,
 37475,
 64183,
 52444,
 69646,
 43755]

### Step 8. Add the column owners to cars

In [49]:
cars['owners'] = owners.tolist()

In [50]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,45646
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,64000
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,66292
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,55892
4,17.0,8,302,140,3449,10.5,70,1,ford torino,31814
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,69756
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,65421
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,24549
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,46498
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,44386
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se,48612
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340,57496
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo,59844
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw),47480
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii,31760
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster,35005
16,18.0,6,199,97,2774,15.5,70,1,amc hornet,55466
17,21.0,6,200,85,2587,16.0,70,1,ford maverick,69229
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510,30859
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,23769
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504,71531
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls,27883
22,25.0,4,104,95,2375,17.5,70,2,saab 99e,46731
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002,65441
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin,36028
25,10.0,8,360,215,4615,14.0,70,1,ford f250,68594
26,10.0,8,307,200,4376,15.0,70,1,chevy c20,72928
27,11.0,8,318,210,4382,13.5,70,1,dodge d200,66696
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d,22224
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510,70591
...,...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon,55068
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door,63958
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback,62762
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se,21623
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix,24012
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura,46084
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl,59952
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l,40286
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l,60592
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom,22044
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser,26175
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l,50845
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe,18624
183,36.0,4,107,75,2205,14.5,82,3,honda accord,17878
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla,46149
185,38.0,4,91,67,1965,15.0,82,3,honda civic,38344
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto),25642
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx,34942
188,25.0,6,181,110,2945,16.4,82,1,buick century limited,70299
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel),44030
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion,44030
191,22.0,6,232,112,2835,14.7,82,1,ford granada l,26962
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt,59198
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2,62642
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro,22850
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,37475
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,64183
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,52444
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,69646
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,43755